import './globals.css'
import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import NavBar from './components/NavBar'

const space_grotesk = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>
        <div className='min-h-screen grid place-content-center bg-blue-950'>
          <div className=' sm:w-[500px] md:w-[60px] lg:w-[700px]'>
            <NavBar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
