import './globals.css'
import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import NavBar from './components/NavBar'

const space_grotesk = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DevFinder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>
        <div className='px-4 min-h-screen grid place-content-center dark:bg-blue-950 bg-blue-50'>
          <div className=' sm:w-[500px] md:w-[600px] lg:w-[700px]'>
            <NavBar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
